// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Gm.proto

package org.wxd.mmo.script.gamesr.gm.message;

public final class Gm {
  private Gm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proto_Gm_ResGmList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proto_Gm_ResGmList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proto_Gm_GmGroup_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proto_Gm_GmGroup_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proto_Gm_GmBean_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proto_Gm_GmBean_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proto_Gm_ReqGm_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proto_Gm_ReqGm_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010Gm.proto\022\010Proto.Gm\".\n\tResGmList\022!\n\006gro" +
      "ups\030\001 \003(\0132\021.Proto.Gm.GmGroup\"7\n\007GmGroup\022" +
      "\r\n\005group\030\001 \001(\t\022\035\n\003gms\030\002 \003(\0132\020.Proto.Gm.G" +
      "mBean\"=\n\006GmBean\022\014\n\004name\030\001 \001(\t\022\017\n\007comment" +
      "\030\002 \001(\t\022\024\n\014defaultValue\030\003 \001(\t\"%\n\005ReqGm\022\014\n" +
      "\004name\030\001 \001(\t\022\016\n\006params\030\002 \001(\tB(\n$org.wxd.m" +
      "mo.script.gamesr.gm.messageP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Proto_Gm_ResGmList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Proto_Gm_ResGmList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proto_Gm_ResGmList_descriptor,
        new java.lang.String[] { "Groups", });
    internal_static_Proto_Gm_GmGroup_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Proto_Gm_GmGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proto_Gm_GmGroup_descriptor,
        new java.lang.String[] { "Group", "Gms", });
    internal_static_Proto_Gm_GmBean_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Proto_Gm_GmBean_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proto_Gm_GmBean_descriptor,
        new java.lang.String[] { "Name", "Comment", "DefaultValue", });
    internal_static_Proto_Gm_ReqGm_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Proto_Gm_ReqGm_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proto_Gm_ReqGm_descriptor,
        new java.lang.String[] { "Name", "Params", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
