// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Gm.proto

package org.wxd.mmo.script.gamesr.gm.message;

public interface GmBeanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Proto.Gm.GmBean)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *gm名称
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   *gm名称
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   *备注说明
   * </pre>
   *
   * <code>string comment = 2;</code>
   * @return The comment.
   */
  java.lang.String getComment();
  /**
   * <pre>
   *备注说明
   * </pre>
   *
   * <code>string comment = 2;</code>
   * @return The bytes for comment.
   */
  com.google.protobuf.ByteString
      getCommentBytes();

  /**
   * <pre>
   *默认参数
   * </pre>
   *
   * <code>string defaultValue = 3;</code>
   * @return The defaultValue.
   */
  java.lang.String getDefaultValue();
  /**
   * <pre>
   *默认参数
   * </pre>
   *
   * <code>string defaultValue = 3;</code>
   * @return The bytes for defaultValue.
   */
  com.google.protobuf.ByteString
      getDefaultValueBytes();
}
