// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Gm.proto

package org.wxd.mmo.script.gamesr.gm.message;

public interface ReqGmOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Proto.Gm.ReqGm)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *gm名称
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   *gm名称
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   *参数
   * </pre>
   *
   * <code>string params = 2;</code>
   * @return The params.
   */
  java.lang.String getParams();
  /**
   * <pre>
   *参数
   * </pre>
   *
   * <code>string params = 2;</code>
   * @return The bytes for params.
   */
  com.google.protobuf.ByteString
      getParamsBytes();
}
