// source: Gm.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.Proto.Gm.GmGroup');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.Proto.Gm.GmBean');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Proto.Gm.GmGroup = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Proto.Gm.GmGroup.repeatedFields_, null);
};
goog.inherits(proto.Proto.Gm.GmGroup, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Proto.Gm.GmGroup.displayName = 'proto.Proto.Gm.GmGroup';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Proto.Gm.GmGroup.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Proto.Gm.GmGroup.prototype.toObject = function(opt_includeInstance) {
  return proto.Proto.Gm.GmGroup.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Proto.Gm.GmGroup} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Proto.Gm.GmGroup.toObject = function(includeInstance, msg) {
  var f, obj = {
    group: jspb.Message.getFieldWithDefault(msg, 1, ""),
    gmsList: jspb.Message.toObjectList(msg.getGmsList(),
    proto.Proto.Gm.GmBean.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Proto.Gm.GmGroup}
 */
proto.Proto.Gm.GmGroup.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Proto.Gm.GmGroup;
  return proto.Proto.Gm.GmGroup.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Proto.Gm.GmGroup} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Proto.Gm.GmGroup}
 */
proto.Proto.Gm.GmGroup.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setGroup(value);
      break;
    case 2:
      var value = new proto.Proto.Gm.GmBean;
      reader.readMessage(value,proto.Proto.Gm.GmBean.deserializeBinaryFromReader);
      msg.addGms(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Proto.Gm.GmGroup.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Proto.Gm.GmGroup.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Proto.Gm.GmGroup} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Proto.Gm.GmGroup.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGroup();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getGmsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.Proto.Gm.GmBean.serializeBinaryToWriter
    );
  }
};


/**
 * optional string group = 1;
 * @return {string}
 */
proto.Proto.Gm.GmGroup.prototype.getGroup = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Proto.Gm.GmGroup} returns this
 */
proto.Proto.Gm.GmGroup.prototype.setGroup = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated GmBean gms = 2;
 * @return {!Array<!proto.Proto.Gm.GmBean>}
 */
proto.Proto.Gm.GmGroup.prototype.getGmsList = function() {
  return /** @type{!Array<!proto.Proto.Gm.GmBean>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Proto.Gm.GmBean, 2));
};


/**
 * @param {!Array<!proto.Proto.Gm.GmBean>} value
 * @return {!proto.Proto.Gm.GmGroup} returns this
*/
proto.Proto.Gm.GmGroup.prototype.setGmsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.Proto.Gm.GmBean=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Proto.Gm.GmBean}
 */
proto.Proto.Gm.GmGroup.prototype.addGms = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.Proto.Gm.GmBean, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Proto.Gm.GmGroup} returns this
 */
proto.Proto.Gm.GmGroup.prototype.clearGmsList = function() {
  return this.setGmsList([]);
};


