/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class System */

#ifndef _Included_System
#define _Included_System
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     System
 * Method:    currentTimeMillis
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_System_currentTimeMillis
  (JNIEnv *, jclass);

/*
 * Class:     System
 * Method:    setOffset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_System_setOffset
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
