/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Timelib */

#ifndef _Included_Timelib
#define _Included_Timelib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Timelib
 * Method:    register
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Timelib_register
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
