// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Chat.proto

package wxdgaming.mmo.script.gamesr.chat.message;

public interface ResChatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Proto.Chat.ResChat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *聊天类型
   * </pre>
   *
   * <code>.Proto.Chat.ChatType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <pre>
   *聊天类型
   * </pre>
   *
   * <code>.Proto.Chat.ChatType type = 1;</code>
   * @return The type.
   */
  wxdgaming.mmo.script.gamesr.chat.message.ChatType getType();

  /**
   * <pre>
   *消息内容
   * </pre>
   *
   * <code>string msg = 2;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <pre>
   *消息内容
   * </pre>
   *
   * <code>string msg = 2;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <pre>
   *发送者id；
   * </pre>
   *
   * <code>int64 sendUid = 3;</code>
   * @return The sendUid.
   */
  long getSendUid();

  /**
   * <pre>
   *发送者名字
   * </pre>
   *
   * <code>string sendName = 4;</code>
   * @return The sendName.
   */
  java.lang.String getSendName();
  /**
   * <pre>
   *发送者名字
   * </pre>
   *
   * <code>string sendName = 4;</code>
   * @return The bytes for sendName.
   */
  com.google.protobuf.ByteString
      getSendNameBytes();
}
