// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Guild.proto

package wxdgaming.mmo.script.gamesr.guild.message;

public interface ReqGuildListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Proto.Login.ReqGuildList)
    com.google.protobuf.MessageOrBuilder {
}
