// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Guild.proto

package wxdgaming.mmo.script.gamesr.guild.message;

public interface ResGuildListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Proto.Login.ResGuildList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *工会唯一ID
   * </pre>
   *
   * <code>int64 uid = 1;</code>
   * @return The uid.
   */
  long getUid();

  /**
   * <pre>
   *工会的名字
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   *工会的名字
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   *工会资金
   * </pre>
   *
   * <code>map&lt;int32, int64&gt; moneys = 3;</code>
   */
  int getMoneysCount();
  /**
   * <pre>
   *工会资金
   * </pre>
   *
   * <code>map&lt;int32, int64&gt; moneys = 3;</code>
   */
  boolean containsMoneys(
      int key);
  /**
   * Use {@link #getMoneysMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, java.lang.Long>
  getMoneys();
  /**
   * <pre>
   *工会资金
   * </pre>
   *
   * <code>map&lt;int32, int64&gt; moneys = 3;</code>
   */
  java.util.Map<java.lang.Integer, java.lang.Long>
  getMoneysMap();
  /**
   * <pre>
   *工会资金
   * </pre>
   *
   * <code>map&lt;int32, int64&gt; moneys = 3;</code>
   */

  long getMoneysOrDefault(
      int key,
      long defaultValue);
  /**
   * <pre>
   *工会资金
   * </pre>
   *
   * <code>map&lt;int32, int64&gt; moneys = 3;</code>
   */

  long getMoneysOrThrow(
      int key);
}
