--- 事件注册，触发
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 無心道(15388152619).
--- DateTime: 2024/10/31 16:54
---

EventListerTable = {

    new          = function()
        local tmp = setmetatable({}, EventListerTable)
        EventListerTable.__index = EventListerTable
        return tmp
    end,

    eventMap     = function(self, eventType)
        eventType = tostring(eventType)
        if not self[eventType] then
            self[eventType] = {}
        end
        return self[eventType]
    end,

    --- 注册事件
    ---@param eventType any 事件类型
    ---@param eventName string 事件名称
    ---@param eventFun function 事件回调函数
    eventLister  = function(self, eventType, eventName, eventFun)
        local em = self:eventMap(eventType)
        if em[eventName] then
            _LUA_Error(debug.traceback("存在相同的事件【" .. eventName .. "】注册"))
            return
        end
        em[eventName] = eventFun
        --gameDebug.printType(_VERSION, "注册事件:", self, em, eventType, eventName)
    end,
    --- 触发事件
    ---@param eventType any 事件类型
    ---@param name string 事件名称
    ---@param ... any 事件参数
    triggerEvent = function(self, eventType, ...)
        local em = self:eventMap(eventType)
        if em then
            for k, v in pairs(em) do
                local s, e = xpcall(v, debug.traceback, ...)
                gameDebug.assertPrintTrace(s, "触发事件", k, "调用异常", e, ...)
            end
        end
    end
}