// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Gm.proto

package wxdgaming.mmo.script.gamesr.gm.message;

public interface ResGmListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Proto.Gm.ResGmList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *所有分组
   * </pre>
   *
   * <code>repeated .Proto.Gm.GmGroup groups = 1;</code>
   */
  java.util.List<GmGroup>
      getGroupsList();
  /**
   * <pre>
   *所有分组
   * </pre>
   *
   * <code>repeated .Proto.Gm.GmGroup groups = 1;</code>
   */
  GmGroup getGroups(int index);
  /**
   * <pre>
   *所有分组
   * </pre>
   *
   * <code>repeated .Proto.Gm.GmGroup groups = 1;</code>
   */
  int getGroupsCount();
  /**
   * <pre>
   *所有分组
   * </pre>
   *
   * <code>repeated .Proto.Gm.GmGroup groups = 1;</code>
   */
  java.util.List<? extends GmGroupOrBuilder>
      getGroupsOrBuilderList();
  /**
   * <pre>
   *所有分组
   * </pre>
   *
   * <code>repeated .Proto.Gm.GmGroup groups = 1;</code>
   */
  GmGroupOrBuilder getGroupsOrBuilder(
      int index);
}
