--- table 操作
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wxdgaming.
--- DateTime: 2024/8/28 17:30
---

function t3(str)
    print("lua 接收 java 传递参数 - " .. tostring(str))
    javaT3("我是 lua")
    return str
end

function testNow(map)
    print("      lua now - " .. map["now"])
    print("   lua nowsec - " .. map["nowsec"])
    print("lua math.ceil - " .. math.ceil(map["now"] / 1000))
end