// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Chat.proto

package org.wxd.mmo.script.gamesr.chat.message;

public interface ReqChatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Proto.Chat.ReqChat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *聊天类型
   * </pre>
   *
   * <code>.Proto.Chat.ChatType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <pre>
   *聊天类型
   * </pre>
   *
   * <code>.Proto.Chat.ChatType type = 1;</code>
   * @return The type.
   */
  org.wxd.mmo.script.gamesr.chat.message.ChatType getType();

  /**
   * <pre>
   *消息内容
   * </pre>
   *
   * <code>string msg = 2;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <pre>
   *消息内容
   * </pre>
   *
   * <code>string msg = 2;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
