---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by troy-chen.
--- DateTime: 2024/7/27 下午11:36
---

function index(info)
    local request = info.request
    local response = info.response
    local body = info.body
    print("request = " .. tostring(request))
    print("response = " .. tostring(response))
    return "lua -- dd"
end