---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by troy-chen.
--- DateTime: 2024/7/27 下午11:36
---

function index(info)
    local request = info.request
    local response = info.response
    local body = info.body
    print("request = " .. tostring(request))
    print("response = " .. tostring(response))
    local var = JsonUtil:toJson(info)
    print(var)
    return "lua -- dd"
end

function paramsTest(p1, p2, p3, p4, p5, p6)
    print("p1 = " .. tostring(p1)
            .. "; p2 = " .. tostring(p2)
            .. "; p3 = " .. tostring(p3)
            .. "; p4 = " .. tostring(p4)
            .. "; p5 = " .. tostring(p5)
    )
    return { "ok", "ok" }
end