// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tips.proto

package wxdgaming.mmo.script.gamesr.tips.message;

/**
 * Protobuf enum {@code Proto.Tips.TipsType}
 */
public enum TipsType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *普通提示
   * </pre>
   *
   * <code>normal = 0;</code>
   */
  normal(0),
  /**
   * <pre>
   *顶部跑马灯
   * </pre>
   *
   * <code>top = 1;</code>
   */
  top(1),
  /**
   * <pre>
   *聊天框提升
   * </pre>
   *
   * <code>chat = 2;</code>
   */
  chat(2),
  /**
   * <pre>
   *正中央红色异常提示
   * </pre>
   *
   * <code>error = 3;</code>
   */
  error(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *普通提示
   * </pre>
   *
   * <code>normal = 0;</code>
   */
  public static final int normal_VALUE = 0;
  /**
   * <pre>
   *顶部跑马灯
   * </pre>
   *
   * <code>top = 1;</code>
   */
  public static final int top_VALUE = 1;
  /**
   * <pre>
   *聊天框提升
   * </pre>
   *
   * <code>chat = 2;</code>
   */
  public static final int chat_VALUE = 2;
  /**
   * <pre>
   *正中央红色异常提示
   * </pre>
   *
   * <code>error = 3;</code>
   */
  public static final int error_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TipsType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TipsType forNumber(int value) {
    switch (value) {
      case 0: return normal;
      case 1: return top;
      case 2: return chat;
      case 3: return error;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TipsType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TipsType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TipsType>() {
          public TipsType findValueByNumber(int number) {
            return TipsType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return Tips.getDescriptor().getEnumTypes().get(0);
  }

  private static final TipsType[] VALUES = values();

  public static TipsType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TipsType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Proto.Tips.TipsType)
}

