--- 测试类和方法调用关系
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 無心道(15388152619).
--- DateTime: 2024/11/4 10:55
---

TestClass = {
    new = function()
        local var = setmetatable({}, TestClass)
        return var
    end
}
TestClass.__index = TestClass

test_map = {}
table.insert(test_map, os.time())
print(test_map)
function TestClass:Name(newName)
    if newName ~= nil then
        self["name"] = newName
    end
    TestClass.Level(self, 2)
    return self["name"]
end

function TestClass:Level(newLv)
    if newLv ~= nil then
        self["level"] = newLv
    end
    return self["level"]
end

function TestClass:printName2()
    print("printName2", self)
end

function ddd()
    print("ddddddd")
end

local test = TestClass.new()
local test2 = TestClass.new()
test:Name("t1")
test:Level(2)

test2:Name("t2")
test2:Level(2)

--TestClass.printName2(test)
--TestClass.printName2(test2)
--TestClass.printName2({ level = 1 })