---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2024/10/28 13:50
---
--- 定义一个类
RechargeData = {

    key = function()
        return "recharge"
    end,

    get = function()
        local obj = getdata(RechargeData.key())
        local var = setmetatable(obj or {}, RechargeData)
        RechargeData.__index = RechargeData
        return var
    end,

    save = function(self)
        setdata(RechargeData.key(), self);
    end,

    --- 增加金额
    totalMoney = function(self, money)
        if self.rechargeTotalMoney == nil then
            self.rechargeTotalMoney = 0;
        end
        if money ~= nil then
            self.rechargeTotalMoney = self.rechargeTotalMoney + money
        end
        return self.rechargeTotalMoney
    end,

}

function printData()
    local rechargeData = RechargeData.get();
    print(type(rechargeData), rechargeData)
    rechargeData:totalMoney(50)
    print(rechargeData:totalMoney())
    rechargeData:save()
    print("==============================")
end
