--- 数据测试
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 無心道(15388152619).
--- DateTime: 2024/11/1 13:38

TestData = {}
TestData.__index = TestData

function TestData.new()
    local tmp = {
        id    = 1,
        name  = "test1",
        level = 1,
    }
    return tmp
end

function TestData.print(data)
    gameDebug.print(data)
end

function TestData.Lv(data, change)
    if change then
        data.level = (data.level or 0) + change
    end
    return data.level or 0
end

function TestData.print2(...)
    local string = gameDebug.toStrings(" ", "dd", ...)
    print(string)
end

local var = TestData.new()
print(TestData.Lv(var, 33))
TestData.print(var)
TestData.print2(var)
gameDebug.assertPrintTrace(var.level == 33, "TestData.Lv(data, change) 测试失败")
gameDebug.assertTrue(var.level == 33, "TestData.Lv(data, change) 测试失败")
