// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Login.proto

package org.wxd.mmo.script.gamesr.login.message;

public interface UserBeanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Proto.Login.UserBean)
    com.google.protobuf.MessageOrBuilder {
}
