server:
  port: 18801
  tomcat:
    max-threads: 200
    min-spare-threads: 10

spring:
  profiles:
    active: thread
  web:
    resources:
      chain:
        cache: false
      static-locations: classpath:/public/
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
      enabled: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?createDatabaseIfNotExist=true
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
task:
  pool:
    corePoolSize: 3
    maxPoolSize: 6
    keepAliveSeconds: 300
    queueCapacity: 50
