---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2024/8/19 09:49
---

function t1()
    local num = 99999999999999999
    print(num)
    print(1)
    --print(1 << 2)
    local time = os.time()
    print(type(time) .. " - " .. tostring(time))
    --print(type(time) + num .. tostring(time))
    local str = "1t"
    print(str, num)
end