// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tips.proto

package org.wxd.mmo.script.gamesr.tips.message;

/**
 * Protobuf type {@code Proto.Tips.ResTips}
 */
public final class ResTips extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Proto.Tips.ResTips)
    ResTipsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResTips.newBuilder() to construct.
  private ResTips(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResTips() {
    type_ = 0;
    lanCode_ = "";
    params_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ResTips();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ResTips(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            lanCode_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              params_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            params_.add(s);
            break;
          }
          case 32: {

            resId_ = input.readSInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        params_ = params_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.wxd.mmo.script.gamesr.tips.message.Tips.internal_static_Proto_Tips_ResTips_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.wxd.mmo.script.gamesr.tips.message.Tips.internal_static_Proto_Tips_ResTips_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.wxd.mmo.script.gamesr.tips.message.ResTips.class, org.wxd.mmo.script.gamesr.tips.message.ResTips.Builder.class);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <pre>
   *0正常提示，1跑马灯，2错误提示
   * </pre>
   *
   * <code>.Proto.Tips.TipsType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <pre>
   *0正常提示，1跑马灯，2错误提示
   * </pre>
   *
   * <code>.Proto.Tips.TipsType type = 1;</code>
   * @return The type.
   */
  @java.lang.Override public org.wxd.mmo.script.gamesr.tips.message.TipsType getType() {
    @SuppressWarnings("deprecation")
    org.wxd.mmo.script.gamesr.tips.message.TipsType result = org.wxd.mmo.script.gamesr.tips.message.TipsType.valueOf(type_);
    return result == null ? org.wxd.mmo.script.gamesr.tips.message.TipsType.UNRECOGNIZED : result;
  }

  public static final int LANCODE_FIELD_NUMBER = 2;
  private volatile java.lang.Object lanCode_;
  /**
   * <pre>
   *如果是纯数字表示是语言包，否者就直接显示
   * </pre>
   *
   * <code>string lanCode = 2;</code>
   * @return The lanCode.
   */
  @java.lang.Override
  public java.lang.String getLanCode() {
    java.lang.Object ref = lanCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lanCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *如果是纯数字表示是语言包，否者就直接显示
   * </pre>
   *
   * <code>string lanCode = 2;</code>
   * @return The bytes for lanCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLanCodeBytes() {
    java.lang.Object ref = lanCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lanCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARAMS_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList params_;
  /**
   * <pre>
   *需要的参数
   * </pre>
   *
   * <code>repeated string params = 3;</code>
   * @return A list containing the params.
   */
  public com.google.protobuf.ProtocolStringList
      getParamsList() {
    return params_;
  }
  /**
   * <pre>
   *需要的参数
   * </pre>
   *
   * <code>repeated string params = 3;</code>
   * @return The count of params.
   */
  public int getParamsCount() {
    return params_.size();
  }
  /**
   * <pre>
   *需要的参数
   * </pre>
   *
   * <code>repeated string params = 3;</code>
   * @param index The index of the element to return.
   * @return The params at the given index.
   */
  public java.lang.String getParams(int index) {
    return params_.get(index);
  }
  /**
   * <pre>
   *需要的参数
   * </pre>
   *
   * <code>repeated string params = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the params at the given index.
   */
  public com.google.protobuf.ByteString
      getParamsBytes(int index) {
    return params_.getByteString(index);
  }

  public static final int RESID_FIELD_NUMBER = 4;
  private int resId_;
  /**
   * <pre>
   *告诉客户端回传消息id，可以取消监听了
   * </pre>
   *
   * <code>sint32 resId = 4;</code>
   * @return The resId.
   */
  @java.lang.Override
  public int getResId() {
    return resId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != org.wxd.mmo.script.gamesr.tips.message.TipsType.normal.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lanCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, lanCode_);
    }
    for (int i = 0; i < params_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, params_.getRaw(i));
    }
    if (resId_ != 0) {
      output.writeSInt32(4, resId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != org.wxd.mmo.script.gamesr.tips.message.TipsType.normal.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lanCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, lanCode_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < params_.size(); i++) {
        dataSize += computeStringSizeNoTag(params_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getParamsList().size();
    }
    if (resId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(4, resId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.wxd.mmo.script.gamesr.tips.message.ResTips)) {
      return super.equals(obj);
    }
    org.wxd.mmo.script.gamesr.tips.message.ResTips other = (org.wxd.mmo.script.gamesr.tips.message.ResTips) obj;

    if (type_ != other.type_) return false;
    if (!getLanCode()
        .equals(other.getLanCode())) return false;
    if (!getParamsList()
        .equals(other.getParamsList())) return false;
    if (getResId()
        != other.getResId()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + LANCODE_FIELD_NUMBER;
    hash = (53 * hash) + getLanCode().hashCode();
    if (getParamsCount() > 0) {
      hash = (37 * hash) + PARAMS_FIELD_NUMBER;
      hash = (53 * hash) + getParamsList().hashCode();
    }
    hash = (37 * hash) + RESID_FIELD_NUMBER;
    hash = (53 * hash) + getResId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.wxd.mmo.script.gamesr.tips.message.ResTips parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.wxd.mmo.script.gamesr.tips.message.ResTips parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.wxd.mmo.script.gamesr.tips.message.ResTips parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.wxd.mmo.script.gamesr.tips.message.ResTips parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.wxd.mmo.script.gamesr.tips.message.ResTips parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.wxd.mmo.script.gamesr.tips.message.ResTips parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.wxd.mmo.script.gamesr.tips.message.ResTips parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.wxd.mmo.script.gamesr.tips.message.ResTips parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.wxd.mmo.script.gamesr.tips.message.ResTips parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.wxd.mmo.script.gamesr.tips.message.ResTips parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.wxd.mmo.script.gamesr.tips.message.ResTips parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.wxd.mmo.script.gamesr.tips.message.ResTips parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.wxd.mmo.script.gamesr.tips.message.ResTips prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Proto.Tips.ResTips}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Proto.Tips.ResTips)
      org.wxd.mmo.script.gamesr.tips.message.ResTipsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.wxd.mmo.script.gamesr.tips.message.Tips.internal_static_Proto_Tips_ResTips_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.wxd.mmo.script.gamesr.tips.message.Tips.internal_static_Proto_Tips_ResTips_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.wxd.mmo.script.gamesr.tips.message.ResTips.class, org.wxd.mmo.script.gamesr.tips.message.ResTips.Builder.class);
    }

    // Construct using org.wxd.mmo.script.gamesr.tips.message.ResTips.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = 0;

      lanCode_ = "";

      params_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      resId_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.wxd.mmo.script.gamesr.tips.message.Tips.internal_static_Proto_Tips_ResTips_descriptor;
    }

    @java.lang.Override
    public org.wxd.mmo.script.gamesr.tips.message.ResTips getDefaultInstanceForType() {
      return org.wxd.mmo.script.gamesr.tips.message.ResTips.getDefaultInstance();
    }

    @java.lang.Override
    public org.wxd.mmo.script.gamesr.tips.message.ResTips build() {
      org.wxd.mmo.script.gamesr.tips.message.ResTips result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.wxd.mmo.script.gamesr.tips.message.ResTips buildPartial() {
      org.wxd.mmo.script.gamesr.tips.message.ResTips result = new org.wxd.mmo.script.gamesr.tips.message.ResTips(this);
      int from_bitField0_ = bitField0_;
      result.type_ = type_;
      result.lanCode_ = lanCode_;
      if (((bitField0_ & 0x00000001) != 0)) {
        params_ = params_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.params_ = params_;
      result.resId_ = resId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.wxd.mmo.script.gamesr.tips.message.ResTips) {
        return mergeFrom((org.wxd.mmo.script.gamesr.tips.message.ResTips)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.wxd.mmo.script.gamesr.tips.message.ResTips other) {
      if (other == org.wxd.mmo.script.gamesr.tips.message.ResTips.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (!other.getLanCode().isEmpty()) {
        lanCode_ = other.lanCode_;
        onChanged();
      }
      if (!other.params_.isEmpty()) {
        if (params_.isEmpty()) {
          params_ = other.params_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureParamsIsMutable();
          params_.addAll(other.params_);
        }
        onChanged();
      }
      if (other.getResId() != 0) {
        setResId(other.getResId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.wxd.mmo.script.gamesr.tips.message.ResTips parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.wxd.mmo.script.gamesr.tips.message.ResTips) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int type_ = 0;
    /**
     * <pre>
     *0正常提示，1跑马灯，2错误提示
     * </pre>
     *
     * <code>.Proto.Tips.TipsType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     *0正常提示，1跑马灯，2错误提示
     * </pre>
     *
     * <code>.Proto.Tips.TipsType type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *0正常提示，1跑马灯，2错误提示
     * </pre>
     *
     * <code>.Proto.Tips.TipsType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public org.wxd.mmo.script.gamesr.tips.message.TipsType getType() {
      @SuppressWarnings("deprecation")
      org.wxd.mmo.script.gamesr.tips.message.TipsType result = org.wxd.mmo.script.gamesr.tips.message.TipsType.valueOf(type_);
      return result == null ? org.wxd.mmo.script.gamesr.tips.message.TipsType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *0正常提示，1跑马灯，2错误提示
     * </pre>
     *
     * <code>.Proto.Tips.TipsType type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(org.wxd.mmo.script.gamesr.tips.message.TipsType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *0正常提示，1跑马灯，2错误提示
     * </pre>
     *
     * <code>.Proto.Tips.TipsType type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object lanCode_ = "";
    /**
     * <pre>
     *如果是纯数字表示是语言包，否者就直接显示
     * </pre>
     *
     * <code>string lanCode = 2;</code>
     * @return The lanCode.
     */
    public java.lang.String getLanCode() {
      java.lang.Object ref = lanCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lanCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *如果是纯数字表示是语言包，否者就直接显示
     * </pre>
     *
     * <code>string lanCode = 2;</code>
     * @return The bytes for lanCode.
     */
    public com.google.protobuf.ByteString
        getLanCodeBytes() {
      java.lang.Object ref = lanCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lanCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *如果是纯数字表示是语言包，否者就直接显示
     * </pre>
     *
     * <code>string lanCode = 2;</code>
     * @param value The lanCode to set.
     * @return This builder for chaining.
     */
    public Builder setLanCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lanCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *如果是纯数字表示是语言包，否者就直接显示
     * </pre>
     *
     * <code>string lanCode = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLanCode() {
      
      lanCode_ = getDefaultInstance().getLanCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *如果是纯数字表示是语言包，否者就直接显示
     * </pre>
     *
     * <code>string lanCode = 2;</code>
     * @param value The bytes for lanCode to set.
     * @return This builder for chaining.
     */
    public Builder setLanCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lanCode_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList params_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureParamsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        params_ = new com.google.protobuf.LazyStringArrayList(params_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     *需要的参数
     * </pre>
     *
     * <code>repeated string params = 3;</code>
     * @return A list containing the params.
     */
    public com.google.protobuf.ProtocolStringList
        getParamsList() {
      return params_.getUnmodifiableView();
    }
    /**
     * <pre>
     *需要的参数
     * </pre>
     *
     * <code>repeated string params = 3;</code>
     * @return The count of params.
     */
    public int getParamsCount() {
      return params_.size();
    }
    /**
     * <pre>
     *需要的参数
     * </pre>
     *
     * <code>repeated string params = 3;</code>
     * @param index The index of the element to return.
     * @return The params at the given index.
     */
    public java.lang.String getParams(int index) {
      return params_.get(index);
    }
    /**
     * <pre>
     *需要的参数
     * </pre>
     *
     * <code>repeated string params = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the params at the given index.
     */
    public com.google.protobuf.ByteString
        getParamsBytes(int index) {
      return params_.getByteString(index);
    }
    /**
     * <pre>
     *需要的参数
     * </pre>
     *
     * <code>repeated string params = 3;</code>
     * @param index The index to set the value at.
     * @param value The params to set.
     * @return This builder for chaining.
     */
    public Builder setParams(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureParamsIsMutable();
      params_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *需要的参数
     * </pre>
     *
     * <code>repeated string params = 3;</code>
     * @param value The params to add.
     * @return This builder for chaining.
     */
    public Builder addParams(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureParamsIsMutable();
      params_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *需要的参数
     * </pre>
     *
     * <code>repeated string params = 3;</code>
     * @param values The params to add.
     * @return This builder for chaining.
     */
    public Builder addAllParams(
        java.lang.Iterable<java.lang.String> values) {
      ensureParamsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, params_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *需要的参数
     * </pre>
     *
     * <code>repeated string params = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearParams() {
      params_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *需要的参数
     * </pre>
     *
     * <code>repeated string params = 3;</code>
     * @param value The bytes of the params to add.
     * @return This builder for chaining.
     */
    public Builder addParamsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureParamsIsMutable();
      params_.add(value);
      onChanged();
      return this;
    }

    private int resId_ ;
    /**
     * <pre>
     *告诉客户端回传消息id，可以取消监听了
     * </pre>
     *
     * <code>sint32 resId = 4;</code>
     * @return The resId.
     */
    @java.lang.Override
    public int getResId() {
      return resId_;
    }
    /**
     * <pre>
     *告诉客户端回传消息id，可以取消监听了
     * </pre>
     *
     * <code>sint32 resId = 4;</code>
     * @param value The resId to set.
     * @return This builder for chaining.
     */
    public Builder setResId(int value) {
      
      resId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *告诉客户端回传消息id，可以取消监听了
     * </pre>
     *
     * <code>sint32 resId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearResId() {
      
      resId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Proto.Tips.ResTips)
  }

  // @@protoc_insertion_point(class_scope:Proto.Tips.ResTips)
  private static final org.wxd.mmo.script.gamesr.tips.message.ResTips DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.wxd.mmo.script.gamesr.tips.message.ResTips();
  }

  public static org.wxd.mmo.script.gamesr.tips.message.ResTips getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResTips>
      PARSER = new com.google.protobuf.AbstractParser<ResTips>() {
    @java.lang.Override
    public ResTips parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ResTips(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResTips> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResTips> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.wxd.mmo.script.gamesr.tips.message.ResTips getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

