// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tips.proto

package org.wxd.mmo.script.gamesr.tips.message;

public interface ResTipsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Proto.Tips.ResTips)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *0正常提示，1跑马灯，2错误提示
   * </pre>
   *
   * <code>sint32 type = 1;</code>
   * @return The type.
   */
  int getType();

  /**
   * <pre>
   *如果是纯数字表示是语言包，否者就直接显示
   * </pre>
   *
   * <code>string lanCode = 2;</code>
   * @return The lanCode.
   */
  java.lang.String getLanCode();
  /**
   * <pre>
   *如果是纯数字表示是语言包，否者就直接显示
   * </pre>
   *
   * <code>string lanCode = 2;</code>
   * @return The bytes for lanCode.
   */
  com.google.protobuf.ByteString
      getLanCodeBytes();

  /**
   * <pre>
   *需要的参数
   * </pre>
   *
   * <code>repeated string params = 3;</code>
   * @return A list containing the params.
   */
  java.util.List<java.lang.String>
      getParamsList();
  /**
   * <pre>
   *需要的参数
   * </pre>
   *
   * <code>repeated string params = 3;</code>
   * @return The count of params.
   */
  int getParamsCount();
  /**
   * <pre>
   *需要的参数
   * </pre>
   *
   * <code>repeated string params = 3;</code>
   * @param index The index of the element to return.
   * @return The params at the given index.
   */
  java.lang.String getParams(int index);
  /**
   * <pre>
   *需要的参数
   * </pre>
   *
   * <code>repeated string params = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the params at the given index.
   */
  com.google.protobuf.ByteString
      getParamsBytes(int index);

  /**
   * <pre>
   *告诉客户端回传消息id，可以取消监听了
   * </pre>
   *
   * <code>sint32 resId = 4;</code>
   * @return The resId.
   */
  int getResId();
}
