// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Guild.proto

package org.wxd.mmo.script.gamesr.guild.message;

public interface ResGuildListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Proto.Login.ResGuildList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *账号
   * </pre>
   *
   * <code>string user = 1;</code>
   * @return The user.
   */
  java.lang.String getUser();
  /**
   * <pre>
   *账号
   * </pre>
   *
   * <code>string user = 1;</code>
   * @return The bytes for user.
   */
  com.google.protobuf.ByteString
      getUserBytes();
}
