// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Guild.proto

package org.wxd.mmo.script.gamesr.guild.message;

/**
 * <pre>
 *公会列表
 * </pre>
 *
 * Protobuf type {@code Proto.Login.ResGuildList}
 */
public final class ResGuildList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Proto.Login.ResGuildList)
    ResGuildListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResGuildList.newBuilder() to construct.
  private ResGuildList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResGuildList() {
    name_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ResGuildList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ResGuildList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            uid_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              moneys_ = com.google.protobuf.MapField.newMapField(
                  MoneysDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Long>
            moneys__ = input.readMessage(
                MoneysDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            moneys_.getMutableMap().put(
                moneys__.getKey(), moneys__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.wxd.mmo.script.gamesr.guild.message.Guild.internal_static_Proto_Login_ResGuildList_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 3:
        return internalGetMoneys();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.wxd.mmo.script.gamesr.guild.message.Guild.internal_static_Proto_Login_ResGuildList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.wxd.mmo.script.gamesr.guild.message.ResGuildList.class, org.wxd.mmo.script.gamesr.guild.message.ResGuildList.Builder.class);
  }

  public static final int UID_FIELD_NUMBER = 1;
  private long uid_;
  /**
   * <pre>
   *工会唯一ID
   * </pre>
   *
   * <code>int64 uid = 1;</code>
   * @return The uid.
   */
  @java.lang.Override
  public long getUid() {
    return uid_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   *工会的名字
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *工会的名字
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MONEYS_FIELD_NUMBER = 3;
  private static final class MoneysDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, java.lang.Long> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, java.lang.Long>newDefaultInstance(
                org.wxd.mmo.script.gamesr.guild.message.Guild.internal_static_Proto_Login_ResGuildList_MoneysEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT32,
                0,
                com.google.protobuf.WireFormat.FieldType.INT64,
                0L);
  }
  private com.google.protobuf.MapField<
      java.lang.Integer, java.lang.Long> moneys_;
  private com.google.protobuf.MapField<java.lang.Integer, java.lang.Long>
  internalGetMoneys() {
    if (moneys_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MoneysDefaultEntryHolder.defaultEntry);
    }
    return moneys_;
  }

  public int getMoneysCount() {
    return internalGetMoneys().getMap().size();
  }
  /**
   * <pre>
   *工会资金
   * </pre>
   *
   * <code>map&lt;int32, int64&gt; moneys = 3;</code>
   */

  @java.lang.Override
  public boolean containsMoneys(
      int key) {
    
    return internalGetMoneys().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMoneysMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.Integer, java.lang.Long> getMoneys() {
    return getMoneysMap();
  }
  /**
   * <pre>
   *工会资金
   * </pre>
   *
   * <code>map&lt;int32, int64&gt; moneys = 3;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.Integer, java.lang.Long> getMoneysMap() {
    return internalGetMoneys().getMap();
  }
  /**
   * <pre>
   *工会资金
   * </pre>
   *
   * <code>map&lt;int32, int64&gt; moneys = 3;</code>
   */
  @java.lang.Override

  public long getMoneysOrDefault(
      int key,
      long defaultValue) {
    
    java.util.Map<java.lang.Integer, java.lang.Long> map =
        internalGetMoneys().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   *工会资金
   * </pre>
   *
   * <code>map&lt;int32, int64&gt; moneys = 3;</code>
   */
  @java.lang.Override

  public long getMoneysOrThrow(
      int key) {
    
    java.util.Map<java.lang.Integer, java.lang.Long> map =
        internalGetMoneys().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (uid_ != 0L) {
      output.writeInt64(1, uid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeIntegerMapTo(
        output,
        internalGetMoneys(),
        MoneysDefaultEntryHolder.defaultEntry,
        3);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (uid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, uid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    for (java.util.Map.Entry<java.lang.Integer, java.lang.Long> entry
         : internalGetMoneys().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Long>
      moneys__ = MoneysDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, moneys__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.wxd.mmo.script.gamesr.guild.message.ResGuildList)) {
      return super.equals(obj);
    }
    org.wxd.mmo.script.gamesr.guild.message.ResGuildList other = (org.wxd.mmo.script.gamesr.guild.message.ResGuildList) obj;

    if (getUid()
        != other.getUid()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!internalGetMoneys().equals(
        other.internalGetMoneys())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUid());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (!internalGetMoneys().getMap().isEmpty()) {
      hash = (37 * hash) + MONEYS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMoneys().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.wxd.mmo.script.gamesr.guild.message.ResGuildList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.wxd.mmo.script.gamesr.guild.message.ResGuildList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.wxd.mmo.script.gamesr.guild.message.ResGuildList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.wxd.mmo.script.gamesr.guild.message.ResGuildList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.wxd.mmo.script.gamesr.guild.message.ResGuildList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.wxd.mmo.script.gamesr.guild.message.ResGuildList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.wxd.mmo.script.gamesr.guild.message.ResGuildList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.wxd.mmo.script.gamesr.guild.message.ResGuildList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.wxd.mmo.script.gamesr.guild.message.ResGuildList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.wxd.mmo.script.gamesr.guild.message.ResGuildList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.wxd.mmo.script.gamesr.guild.message.ResGuildList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.wxd.mmo.script.gamesr.guild.message.ResGuildList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.wxd.mmo.script.gamesr.guild.message.ResGuildList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *公会列表
   * </pre>
   *
   * Protobuf type {@code Proto.Login.ResGuildList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Proto.Login.ResGuildList)
      org.wxd.mmo.script.gamesr.guild.message.ResGuildListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.wxd.mmo.script.gamesr.guild.message.Guild.internal_static_Proto_Login_ResGuildList_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMoneys();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMutableMoneys();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.wxd.mmo.script.gamesr.guild.message.Guild.internal_static_Proto_Login_ResGuildList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.wxd.mmo.script.gamesr.guild.message.ResGuildList.class, org.wxd.mmo.script.gamesr.guild.message.ResGuildList.Builder.class);
    }

    // Construct using org.wxd.mmo.script.gamesr.guild.message.ResGuildList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      uid_ = 0L;

      name_ = "";

      internalGetMutableMoneys().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.wxd.mmo.script.gamesr.guild.message.Guild.internal_static_Proto_Login_ResGuildList_descriptor;
    }

    @java.lang.Override
    public org.wxd.mmo.script.gamesr.guild.message.ResGuildList getDefaultInstanceForType() {
      return org.wxd.mmo.script.gamesr.guild.message.ResGuildList.getDefaultInstance();
    }

    @java.lang.Override
    public org.wxd.mmo.script.gamesr.guild.message.ResGuildList build() {
      org.wxd.mmo.script.gamesr.guild.message.ResGuildList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.wxd.mmo.script.gamesr.guild.message.ResGuildList buildPartial() {
      org.wxd.mmo.script.gamesr.guild.message.ResGuildList result = new org.wxd.mmo.script.gamesr.guild.message.ResGuildList(this);
      int from_bitField0_ = bitField0_;
      result.uid_ = uid_;
      result.name_ = name_;
      result.moneys_ = internalGetMoneys();
      result.moneys_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.wxd.mmo.script.gamesr.guild.message.ResGuildList) {
        return mergeFrom((org.wxd.mmo.script.gamesr.guild.message.ResGuildList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.wxd.mmo.script.gamesr.guild.message.ResGuildList other) {
      if (other == org.wxd.mmo.script.gamesr.guild.message.ResGuildList.getDefaultInstance()) return this;
      if (other.getUid() != 0L) {
        setUid(other.getUid());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      internalGetMutableMoneys().mergeFrom(
          other.internalGetMoneys());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.wxd.mmo.script.gamesr.guild.message.ResGuildList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.wxd.mmo.script.gamesr.guild.message.ResGuildList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long uid_ ;
    /**
     * <pre>
     *工会唯一ID
     * </pre>
     *
     * <code>int64 uid = 1;</code>
     * @return The uid.
     */
    @java.lang.Override
    public long getUid() {
      return uid_;
    }
    /**
     * <pre>
     *工会唯一ID
     * </pre>
     *
     * <code>int64 uid = 1;</code>
     * @param value The uid to set.
     * @return This builder for chaining.
     */
    public Builder setUid(long value) {
      
      uid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *工会唯一ID
     * </pre>
     *
     * <code>int64 uid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUid() {
      
      uid_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     *工会的名字
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *工会的名字
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *工会的名字
     * </pre>
     *
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *工会的名字
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *工会的名字
     * </pre>
     *
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.Long> moneys_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Long>
    internalGetMoneys() {
      if (moneys_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MoneysDefaultEntryHolder.defaultEntry);
      }
      return moneys_;
    }
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Long>
    internalGetMutableMoneys() {
      onChanged();;
      if (moneys_ == null) {
        moneys_ = com.google.protobuf.MapField.newMapField(
            MoneysDefaultEntryHolder.defaultEntry);
      }
      if (!moneys_.isMutable()) {
        moneys_ = moneys_.copy();
      }
      return moneys_;
    }

    public int getMoneysCount() {
      return internalGetMoneys().getMap().size();
    }
    /**
     * <pre>
     *工会资金
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; moneys = 3;</code>
     */

    @java.lang.Override
    public boolean containsMoneys(
        int key) {
      
      return internalGetMoneys().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMoneysMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Long> getMoneys() {
      return getMoneysMap();
    }
    /**
     * <pre>
     *工会资金
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; moneys = 3;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.Integer, java.lang.Long> getMoneysMap() {
      return internalGetMoneys().getMap();
    }
    /**
     * <pre>
     *工会资金
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; moneys = 3;</code>
     */
    @java.lang.Override

    public long getMoneysOrDefault(
        int key,
        long defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.Long> map =
          internalGetMoneys().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *工会资金
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; moneys = 3;</code>
     */
    @java.lang.Override

    public long getMoneysOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.Long> map =
          internalGetMoneys().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearMoneys() {
      internalGetMutableMoneys().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     *工会资金
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; moneys = 3;</code>
     */

    public Builder removeMoneys(
        int key) {
      
      internalGetMutableMoneys().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Long>
    getMutableMoneys() {
      return internalGetMutableMoneys().getMutableMap();
    }
    /**
     * <pre>
     *工会资金
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; moneys = 3;</code>
     */
    public Builder putMoneys(
        int key,
        long value) {
      
      
      internalGetMutableMoneys().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     *工会资金
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; moneys = 3;</code>
     */

    public Builder putAllMoneys(
        java.util.Map<java.lang.Integer, java.lang.Long> values) {
      internalGetMutableMoneys().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Proto.Login.ResGuildList)
  }

  // @@protoc_insertion_point(class_scope:Proto.Login.ResGuildList)
  private static final org.wxd.mmo.script.gamesr.guild.message.ResGuildList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.wxd.mmo.script.gamesr.guild.message.ResGuildList();
  }

  public static org.wxd.mmo.script.gamesr.guild.message.ResGuildList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResGuildList>
      PARSER = new com.google.protobuf.AbstractParser<ResGuildList>() {
    @java.lang.Override
    public ResGuildList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ResGuildList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResGuildList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResGuildList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.wxd.mmo.script.gamesr.guild.message.ResGuildList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

